spring:
  application:
    name: uaa
server:
  port: 9999
logging:
  level:
    org.springframework: warn
    org.springframework.security: warn
security:
  user:
    name: admin
    password: password