spring:
  application:
    name: uaa
server:
  port: 9999
logging:
  level:
    org.springframework: warn
    org.springframework.security: debug
security:
  user:
    name: admin
    password: password
google:
  client:
    client-id: 105604704556-ndv0vsklc25nqjargruera8co92nb7kd.apps.googleusercontent.com
    client-secret: ouwbyn7DEhwfNB3CgAN42_mE
    access-token-uri: https://accounts.google.com/o/oauth2/token
    token-name: access_token
    user-authorization-uri: https://accounts.google.com/o/oauth2/auth
    client-authentication-scheme: form
    scope: https://www.googleapis.com/auth/userinfo.profile,email
  resource:
    user-info-uri: https://www.googleapis.com/oauth2/v1/userinfo?alt=json