spring:
  application:
    name: uaa
server:
  port: 8080
logging:
  level:
    org.springframework: warn
    org.springframework.security: warn
security:
  user:
    name: admin
    password: password
google:
  client:
    client-id: 152974219409-uotglq83dmvks07jpfmrvnb0dahek614.apps.googleusercontent.com
    client-secret: Yx-e-ROwAs2G639NdyI8wXh-
    access-token-uri: https://www.googleapis.com/oauth2/v4/token
    token-name: access_token
    user-authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
    client-authentication-scheme: form
    scope: https://www.googleapis.com/auth/userinfo.profile
  resource:
    user-info-uri: https://www.googleapis.com/oauth2/v1/userinfo?alt=json